// 48 equipos clasificados al Mundial 2026 (sorteo oficial 5 dic 2025).
// rank = posición relativa entre estos 48 según el ranking FIFA (abril 2026).
// group = grupo del sorteo (A–L).
const TEAMS = [
  { id: "francia",         name: "Francia",         rank: 1,  flag: "🇫🇷", cc: "fr",     color: "#002395", group: "I" },
  { id: "espana",          name: "España",          rank: 2,  flag: "🇪🇸", cc: "es",     color: "#C1272D", group: "H" },
  { id: "argentina",       name: "Argentina",       rank: 3,  flag: "🇦🇷", cc: "ar",     color: "#6CACE4", group: "J" },
  { id: "inglaterra",      name: "Inglaterra",      rank: 4,  flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", cc: "gb-eng", color: "#CE1126", group: "L" },
  { id: "portugal",        name: "Portugal",        rank: 5,  flag: "🇵🇹", cc: "pt",     color: "#046A38", group: "K" },
  { id: "brasil",          name: "Brasil",          rank: 6,  flag: "🇧🇷", cc: "br",     color: "#FEDF00", group: "C" },
  { id: "paises_bajos",    name: "Países Bajos",    rank: 7,  flag: "🇳🇱", cc: "nl",     color: "#FF4F00", group: "F" },
  { id: "marruecos",       name: "Marruecos",       rank: 8,  flag: "🇲🇦", cc: "ma",     color: "#C1272D", group: "C" },
  { id: "belgica",         name: "Bélgica",         rank: 9,  flag: "🇧🇪", cc: "be",     color: "#C8102E", group: "G" },
  { id: "alemania",        name: "Alemania",        rank: 10, flag: "🇩🇪", cc: "de",     color: "#1A1A1A", group: "E" },
  { id: "croacia",         name: "Croacia",         rank: 11, flag: "🇭🇷", cc: "hr",     color: "#FF0000", group: "L" },
  { id: "colombia",        name: "Colombia",        rank: 12, flag: "🇨🇴", cc: "co",     color: "#FCD116", group: "K" },
  { id: "senegal",         name: "Senegal",         rank: 13, flag: "🇸🇳", cc: "sn",     color: "#00853F", group: "I" },
  { id: "mexico",          name: "México",          rank: 14, flag: "🇲🇽", cc: "mx",     color: "#006847", group: "A" },
  { id: "usa",             name: "Estados Unidos",  rank: 15, flag: "🇺🇸", cc: "us",     color: "#002868", group: "D" },
  { id: "uruguay",         name: "Uruguay",         rank: 16, flag: "🇺🇾", cc: "uy",     color: "#43A1D5", group: "H" },
  { id: "japon",           name: "Japón",           rank: 17, flag: "🇯🇵", cc: "jp",     color: "#BC002D", group: "F" },
  { id: "suiza",           name: "Suiza",           rank: 18, flag: "🇨🇭", cc: "ch",     color: "#D52B1E", group: "B" },
  { id: "iran",            name: "Irán",            rank: 19, flag: "🇮🇷", cc: "ir",     color: "#239E46", group: "G" },
  { id: "turquia",         name: "Turquía",         rank: 20, flag: "🇹🇷", cc: "tr",     color: "#E30A17", group: "D" },
  { id: "ecuador",         name: "Ecuador",         rank: 21, flag: "🇪🇨", cc: "ec",     color: "#FFDD00", group: "E" },
  { id: "austria",         name: "Austria",         rank: 22, flag: "🇦🇹", cc: "at",     color: "#ED2939", group: "J" },
  { id: "corea_sur",       name: "Corea del Sur",   rank: 23, flag: "🇰🇷", cc: "kr",     color: "#C60C30", group: "A" },
  { id: "australia",       name: "Australia",       rank: 24, flag: "🇦🇺", cc: "au",     color: "#00843D", group: "D" },
  { id: "argelia",         name: "Argelia",         rank: 25, flag: "🇩🇿", cc: "dz",     color: "#007229", group: "J" },
  { id: "egipto",          name: "Egipto",          rank: 26, flag: "🇪🇬", cc: "eg",     color: "#C09300", group: "G" },
  { id: "canada",          name: "Canadá",          rank: 27, flag: "🇨🇦", cc: "ca",     color: "#FF0000", group: "B" },
  { id: "noruega",         name: "Noruega",         rank: 28, flag: "🇳🇴", cc: "no",     color: "#BA0C2F", group: "I" },
  { id: "panama",          name: "Panamá",          rank: 29, flag: "🇵🇦", cc: "pa",     color: "#DA121A", group: "L" },
  { id: "costa_marfil",    name: "Costa de Marfil", rank: 30, flag: "🇨🇮", cc: "ci",     color: "#FF8200", group: "E" },
  { id: "suecia",          name: "Suecia",          rank: 31, flag: "🇸🇪", cc: "se",     color: "#006AA7", group: "F" },
  { id: "paraguay",        name: "Paraguay",        rank: 32, flag: "🇵🇾", cc: "py",     color: "#D52B1E", group: "D" },
  { id: "chequia",         name: "Chequia",         rank: 33, flag: "🇨🇿", cc: "cz",     color: "#11457E", group: "A" },
  { id: "escocia",         name: "Escocia",         rank: 34, flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", cc: "gb-sct", color: "#0065BF", group: "C" },
  { id: "tunez",           name: "Túnez",           rank: 35, flag: "🇹🇳", cc: "tn",     color: "#E70013", group: "F" },
  { id: "rd_congo",        name: "RD Congo",        rank: 36, flag: "🇨🇩", cc: "cd",     color: "#00A2DE", group: "K" },
  { id: "uzbekistan",      name: "Uzbekistán",      rank: 37, flag: "🇺🇿", cc: "uz",     color: "#1EB53A", group: "K" },
  { id: "qatar",           name: "Qatar",           rank: 38, flag: "🇶🇦", cc: "qa",     color: "#8A1538", group: "B" },
  { id: "irak",            name: "Irak",            rank: 39, flag: "🇮🇶", cc: "iq",     color: "#007A3D", group: "I" },
  { id: "sudafrica",       name: "Sudáfrica",       rank: 40, flag: "🇿🇦", cc: "za",     color: "#007A4D", group: "A" },
  { id: "arabia_saudita",  name: "Arabia Saudita",  rank: 41, flag: "🇸🇦", cc: "sa",     color: "#006C35", group: "H" },
  { id: "jordania",        name: "Jordania",        rank: 42, flag: "🇯🇴", cc: "jo",     color: "#C1272D", group: "J" },
  { id: "bosnia",          name: "Bosnia",          rank: 43, flag: "🇧🇦", cc: "ba",     color: "#002F6C", group: "B" },
  { id: "cabo_verde",      name: "Cabo Verde",      rank: 44, flag: "🇨🇻", cc: "cv",     color: "#003893", group: "H" },
  { id: "ghana",           name: "Ghana",           rank: 45, flag: "🇬🇭", cc: "gh",     color: "#006B3F", group: "L" },
  { id: "curazao",         name: "Curazao",         rank: 46, flag: "🇨🇼", cc: "cw",     color: "#002B7F", group: "E" },
  { id: "haiti",           name: "Haití",           rank: 47, flag: "🇭🇹", cc: "ht",     color: "#00209F", group: "C" },
  { id: "nueva_zelanda",   name: "Nueva Zelanda",   rank: 48, flag: "🇳🇿", cc: "nz",     color: "#1A1A1A", group: "G" }
];

// Grupos del Mundial 2026 (orden de bombo en el sorteo).
const GROUPS = {
  A: ["mexico", "sudafrica", "corea_sur", "chequia"],
  B: ["canada", "bosnia", "qatar", "suiza"],
  C: ["brasil", "marruecos", "haiti", "escocia"],
  D: ["usa", "paraguay", "australia", "turquia"],
  E: ["alemania", "curazao", "costa_marfil", "ecuador"],
  F: ["paises_bajos", "japon", "suecia", "tunez"],
  G: ["belgica", "egipto", "iran", "nueva_zelanda"],
  H: ["espana", "cabo_verde", "arabia_saudita", "uruguay"],
  I: ["francia", "senegal", "irak", "noruega"],
  J: ["argentina", "argelia", "austria", "jordania"],
  K: ["portugal", "rd_congo", "uzbekistan", "colombia"],
  L: ["inglaterra", "croacia", "ghana", "panama"]
};
